### ISSUE TITLE
[Priority] Start page

### ISSUE THREAD

**Issue by DaniellMesquita** [AnthyG/ThunderWave#108] opened 2018-08-15 03:37 UTC

**Comment by AnthyG** [comment] 2018-08-15 19:13
This is a duplicate of #65.
If not, please consider explaining further.

**Closed by AnthyG** 2018-08-15 19:13 UTC

**Comment by DaniellMesquita** [comment] 2018-08-15 22:30
I already explained it on Git Center.

**Comment by DaniellMesquita** [comment] 2018-08-15 22:35
Start page with messages history and "New message" button.
User can also pin messages in this page.

**Comment by krixano** [comment] 2018-09-02 19:08
He was saying if it's **not a duplicate** then explain.
